language: node_js
node_js:
  - "0.10"
  - "0.11"
before_script:
  - npm install -g grunt-cli
  - npm install -g karma-cli
  - npm install -g bower
  - bower install
matrix:
  allow_failures:
    - node_js: "0.11"
notifications:
  email: false
